name: check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "Florian Pfleiderer"
        git config --global user.email "florian@pfleiderer.at"

    - name: Checkout PR
      run: |
        git fetch origin refs/pull/${{ github.event.pull_request.number }}/head:pr-${{ github.event.pull_request.number }}
